export const PUBLIC_ROUTES = {
	SIGNIN: '/',
	FORGOT_PASSWORD: 'forgot-password',
	RESET_PASSWORD: 'password-reset/:id/:token',
};

export const PRIVATE_ROUTES = {
	DASHBOARD: '',
	CREATE: 'create',
	PARAM_ID: ':id',
	TOURS: 'tours',
	TOURS_CREATE: 'tours/create',
	TOURS_UPDATE: 'tours/edit/:id',
	TOURS_TYPES: 'tours/types',
	TOURS_TYPES_CREATE: 'tours/types/create',
	TOURS_TYPES_UPDATE: 'tours/types/edit/:id',
	SUPPLEMENTS: 'supplements',
	SUPPLEMENTS_CATEGORIES: 'supplements/categories',
	USERS: 'users',
	REPORTS: 'reports',
	TRANSACTIONS: 'transactions',
	TICKETS: 'tickets',
	TICKETS_LOCATIONS: 'tickets/locations',
	TICKETS_SUPPLIERS: 'tickets/suppliers',
	SETTINGS: 'settings',
	SETTINGS_CURRENCIES: 'settings/currencies',
	USER_ROLES: 'user-roles',
	CATEGORIES: 'categories',
	AIRPORTS: 'airports',
	LOCATIONS_SETTINGS: 'locations-settings',
	LOCATIONS: 'locations',
	TERRITORRIES: 'territorries',
	SUPPLIERS: 'suppliers',
	SETTINGS_PROFILE: 'settings/profile',
	CONFIGURATION: 'configuration',
	ACCOMMODATIONS: 'accommodations',
	PROFILE: 'profile',
};
