export const locationsData = [
	{
		id: 11,
		name: 'Arlanda',
		transportation_type: 1,
		transportation_type_name: 'Air',
		short_code: 'ARL',
		is_active: true,
	},
	{
		id: 3,
		name: 'Gothenburg',
		transportation_type: 1,
		transportation_type_name: 'Air',
		short_code: '1155',
		is_active: true,
	},
	{
		id: 8,
		name: 'Malmo',
		transportation_type: 3,
		transportation_type_name: 'Train',
		short_code: '66',
		is_active: true,
	},
	{
		id: 5,
		name: 'Malmo',
		transportation_type: 2,
		transportation_type_name: 'Bus',
		short_code: '3333',
		is_active: true,
	},
	{
		id: 6,
		name: 'Sollentuna',
		transportation_type: 3,
		transportation_type_name: 'Train',
		short_code: '3344',
		is_active: true,
	},
	{
		id: 10,
		name: 'Stockholm',
		transportation_type: 1,
		transportation_type_name: 'Air',
		short_code: 'STO',
		is_active: true,
	},
	{
		id: 2,
		name: 'Umea',
		transportation_type: 1,
		transportation_type_name: 'Air',
		short_code: '1122',
		is_active: true,
	},
	{
		id: 7,
		name: 'Uppsala',
		transportation_type: 2,
		transportation_type_name: 'Bus',
		short_code: '55',
		is_active: true,
	},
	{
		id: 4,
		name: 'Uppsala Airport',
		transportation_type: 1,
		transportation_type_name: 'Air',
		short_code: '1155',
		is_active: true,
	},
];

export const ticketsData = [
	{
		id: 47,
		start_date: '2022-08-13',
		end_date: '2022-08-20',
		assigned_tickets: 3,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 8,
		departure_station_name: 'Malmo',
		destination: 3,
		destination_station_name: 'Gothenburg',
		pnr: '121213',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 7,
		note: 'na',
	},
	{
		id: 46,
		start_date: '2022-06-01',
		end_date: '2022-06-07',
		assigned_tickets: 2,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 3,
		departure_station_name: 'Gothenburg',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '11222',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 8,
		note: null,
	},
	{
		id: 45,
		start_date: '2022-08-13',
		end_date: '2022-08-20',
		assigned_tickets: 2,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 8,
		departure_station_name: 'Malmo',
		destination: 3,
		destination_station_name: 'Gothenburg',
		pnr: '11222',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 8,
		note: null,
	},
	{
		id: 44,
		start_date: '2022-07-01',
		end_date: '2022-07-07',
		assigned_tickets: 1,
		week_number: null,
		number_of_tickets: 50,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 11,
		departure_station_name: 'Arlanda',
		destination: 3,
		destination_station_name: 'Gothenburg',
		pnr: '1234',
		transportation_company: 11,
		transportation_company_name: 'SAS',
		available_tickets: 49,
		note: 'Morning flights',
	},
	{
		id: 43,
		start_date: '2022-04-29',
		end_date: '2022-05-18',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 5,
		departure_station_name: 'Malmo',
		destination: 10,
		destination_station_name: 'Stockholm',
		pnr: '6666',
		transportation_company: 6,
		transportation_company_name: 'Norwegian',
		available_tickets: 5,
		note: null,
	},
	{
		id: 42,
		start_date: '2022-05-16',
		end_date: '2022-05-22',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 5,
		departure_station_name: 'Malmo',
		destination: 7,
		destination_station_name: 'Uppsala',
		pnr: '4555',
		transportation_company: 8,
		transportation_company_name: 'Malmo Central Station',
		available_tickets: 5,
		note: null,
	},
	{
		id: 41,
		start_date: '2022-05-23',
		end_date: '2022-05-30',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 6,
		departure_station_name: 'Sollentuna',
		destination: 5,
		destination_station_name: 'Malmo',
		pnr: '5666',
		transportation_company: 8,
		transportation_company_name: 'Malmo Central Station',
		available_tickets: 5,
		note: null,
	},
	{
		id: 40,
		start_date: '2022-04-21',
		end_date: '2022-04-26',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 10,
		departure_station_name: 'Stockholm',
		destination: 2,
		destination_station_name: 'Umea',
		pnr: '2323',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 5,
		note: null,
	},
	{
		id: 39,
		start_date: '2022-04-26',
		end_date: '2022-05-03',
		assigned_tickets: 1,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 10,
		departure_station_name: 'Stockholm',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '3434',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 4,
		note: null,
	},
	{
		id: 38,
		start_date: '2022-04-26',
		end_date: '2022-05-03',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 6,
		departure_station_name: 'Sollentuna',
		destination: 5,
		destination_station_name: 'Malmo',
		pnr: '45454',
		transportation_company: 8,
		transportation_company_name: 'Malmo Central Station',
		available_tickets: 5,
		note: null,
	},
	{
		id: 37,
		start_date: '2022-04-26',
		end_date: '2022-05-05',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 9,
		departure_station_name: 'Umea',
		destination: 5,
		destination_station_name: 'Malmo',
		pnr: '3344',
		transportation_company: 8,
		transportation_company_name: 'Malmo Central Station',
		available_tickets: 5,
		note: null,
	},
	{
		id: 36,
		start_date: '2022-04-26',
		end_date: '2022-05-03',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 2,
		transportation_type_name: 'Bus',
		departure: 3,
		departure_station_name: 'Gothenburg',
		destination: 10,
		destination_station_name: 'Stockholm',
		pnr: '4455',
		transportation_company: 9,
		transportation_company_name: 'Red Coach',
		available_tickets: 10,
		note: null,
	},
	{
		id: 35,
		start_date: '2022-04-21',
		end_date: '2022-04-26',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 5,
		departure_station_name: 'Malmo',
		destination: 10,
		destination_station_name: 'Stockholm',
		pnr: '1122',
		transportation_company: 1,
		transportation_company_name: 'Ainul1',
		available_tickets: 10,
		note: null,
	},
	{
		id: 34,
		start_date: '2022-08-15',
		end_date: '2022-08-21',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 19,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 5,
		departure_station_name: 'Malmo',
		destination: 7,
		destination_station_name: 'Uppsala',
		pnr: 'EAtc',
		transportation_company: 6,
		transportation_company_name: 'Norwegian',
		available_tickets: 19,
		note: null,
	},
	{
		id: 33,
		start_date: '2022-06-25',
		end_date: '2022-06-01',
		assigned_tickets: 4,
		week_number: null,
		number_of_tickets: 12,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 10,
		departure_station_name: 'Stockholm',
		destination: 3,
		destination_station_name: 'Gothenburg',
		pnr: '12121ds',
		transportation_company: 5,
		transportation_company_name: 'SAS',
		available_tickets: 8,
		note: 'night',
	},
	{
		id: 25,
		start_date: '2022-05-23',
		end_date: '2022-05-30',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 9,
		departure_station_name: 'Umea',
		destination: 5,
		destination_station_name: 'Malmo',
		pnr: '121',
		transportation_company: 3,
		transportation_company_name: 'Turkish',
		available_tickets: 10,
		note: null,
	},
	{
		id: 24,
		start_date: '2022-05-16',
		end_date: '2022-05-22',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 7,
		departure_station_name: 'Uppsala',
		destination: 9,
		destination_station_name: 'Umea',
		pnr: '23232',
		transportation_company: 3,
		transportation_company_name: 'Turkish',
		available_tickets: 10,
		note: null,
	},
	{
		id: 23,
		start_date: '2022-05-08',
		end_date: '2022-05-15',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 6,
		departure_station_name: 'Sollentuna',
		destination: 3,
		destination_station_name: 'Gothenburg',
		pnr: '12212',
		transportation_company: 3,
		transportation_company_name: 'Turkish',
		available_tickets: 10,
		note: null,
	},
	{
		id: 22,
		start_date: '2022-04-30',
		end_date: '2022-05-07',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 9,
		departure_station_name: 'Umea',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '3343',
		transportation_company: 3,
		transportation_company_name: 'Turkish',
		available_tickets: 10,
		note: null,
	},
	{
		id: 21,
		start_date: '2022-04-22',
		end_date: '2022-04-29',
		assigned_tickets: 1,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 3,
		transportation_type_name: 'Train',
		departure: 6,
		departure_station_name: 'Sollentuna',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '2323',
		transportation_company: 3,
		transportation_company_name: 'Turkish',
		available_tickets: 9,
		note: null,
	},
	{
		id: 17,
		start_date: '2022-05-07',
		end_date: '2022-05-14',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 2,
		transportation_type_name: 'Bus',
		departure: 6,
		departure_station_name: 'Sollentuna',
		destination: 5,
		destination_station_name: 'Malmo',
		pnr: '2223',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 10,
		note: null,
	},
	{
		id: 16,
		start_date: '2022-05-01',
		end_date: '2022-05-07',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 2,
		transportation_type_name: 'Bus',
		departure: 7,
		departure_station_name: 'Uppsala',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '12121',
		transportation_company: 2,
		transportation_company_name: 'Emirates',
		available_tickets: 10,
		note: null,
	},
	{
		id: 10,
		start_date: '2022-04-27',
		end_date: '2022-05-03',
		assigned_tickets: 1,
		week_number: null,
		number_of_tickets: 10,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 9,
		departure_station_name: 'Umea',
		destination: 8,
		destination_station_name: 'Malmo',
		pnr: '5566',
		transportation_company: 1,
		transportation_company_name: 'Ainul1',
		available_tickets: 9,
		note: null,
	},
	{
		id: 6,
		start_date: '2022-04-29',
		end_date: '2022-05-18',
		assigned_tickets: 0,
		week_number: null,
		number_of_tickets: 5,
		transportation_type: 1,
		transportation_type_name: 'Air',
		departure: 3,
		departure_station_name: 'Gothenburg',
		destination: 6,
		destination_station_name: 'Sollentuna',
		pnr: '2233',
		transportation_company: 1,
		transportation_company_name: 'Ainul1',
		available_tickets: 5,
		note: null,
	},
];
